### PR TITLE
Check in CI that the README was Re-Generated

### PR DESCRIPTION
**Pull request by jGleitz**
______________________________________
I confirm that I have read the [Contributor Agreements v1.0](https://github.com/robstoll/atrium/blob/master/.github/Contributor%20Agreements%20v1.0.txt), agree to be bound on them and confirm that my contribution is compliant.

### CODE REVIEW

**Review by robstoll — APPROVED** [review]

**Comment by robstoll** [comment]
Actually, we cannot/should not add this check and I remember why I have not establish it in the first place. Contributors using a different OS than ubuntu would always get this error.

**Review by robstoll — CHANGES_REQUESTED** [review]
Therefore I suggest we either close this PR or we tweak the report of Path assertions that it outputs always the same paths which is quite a hack though

**Comment by jGleitz** [comment]
Ah, I remember. 

How about this: the CI always updates the `README` on `master` after pushes to master?

**Comment by robstoll** [comment]
Why not, but I prefer if a PR is created if needed instead of directly pushing to master

**Comment by robstoll** [comment]
Implemented the creation of a PR in case of a diff in readme (see https://github.com/robstoll/atrium/pull/757). therefore closing this

**Pull request closed without merging**
