### PR TITLE
pairAssertions for the new infix API

### PR DESCRIPTION
**Pull request by dexpota**
I am working on issue #231 and I have a question for the following point described in the issue.

> - copy the PairFeatureAssertionsSpec.kt from atrium-api-fluent-en_GB-common to atrium-api-infix- en_GB-common
>   - introduce a function in the companion object for each assertion function so that we see the infix API in action (see AnyAssertionsSpec for an example)

I copied `PairFeatureAssertionsSpec.kt` from `atrium-api-fluent-en_GB-common` to `atrium-api-infix-> en_GB-common` but I don't understand the second nested point "introduce a function in the companion object for each assertion function ...". 

In the first point I simply defined two infix functions `first` and `second`. Should I define two functions inside the companion object for testing these two?

**EDIT**
I confirm that I have read the Contributor Agreements v1.0, agree to be bound on them and confirm that my contribution is compliant.

### CODE REVIEW

**Comment by robstoll** [comment]
@dexpota have a look into PairFeatureAssertionsSpec in api-cc-infix-en_GB-common (https://github.com/robstoll/atrium/blob/master/apis/cc-infix-en_GB/atrium-api-cc-infix-en_GB-jvm/src/test/kotlin/ch/tutteli/atrium/api/cc/infix/en_GB/PairFeatureAssertionsSpec.kt) the goal is to use the infix api (line 28 and 31)

**Comment by robstoll** [comment]
LGTM, as you still have it marked as WIP I am not going to merge. Please let me know once you are ready

**Comment by dexpota** [comment]
Sorry I was busy in the last days. I removed the WIP mark from the title. I think I did everything to address the issue. If something is missing let me know.

Any feedback on the code is also welcomed :+1:

**Comment by robstoll** [comment]
@dexpota thanks for the contribution :+1: 
Fancy another one?
https://github.com/robstoll/atrium/issues?q=is%3Aopen+is%3Aissue+no%3Aassignee+label%3Ahacktoberfest

**Pull request merged**
