### PR TITLE
Create a sample project for Atrium + junit5 #80

### PR DESCRIPTION
**Pull request by bsemexan**
----
I confirm that I have read the [Contributor Agreements v1.0](https://github.com/robstoll/atrium/blob/master/.github/Contributor%20Agreements%20v1.0.txt), agree to be bound on them and confirm that my contribution is compliant.

### CODE REVIEW

**Comment by robstoll** [comment]
You still have the .idea folder added to the commit.

**Comment by robstoll** [comment]
Try the following:
- open up a terminal in the root of your project
- mv .idea ../atrium-idea
- git add .
- git commit -m "remove idea folder"
- git push
- git mv ../atrium-idea ./.idea

**Comment by bsemexan** [comment]
git mv ../atrium-idea ./.idea
fatal: '../atrium-idea' is outside repository

**Comment by robstoll** [comment]
There were too many files before, I have not seen that you also still had the .gradle folder committed. Do the same as with .idea folder:
```
mv .gradle ../atrium-gradle
git add .
git commit -m "remove .gradle folder"
git push
mv ../atrium-gradle ./.gradle
```

**Comment by bsemexan** [comment]
any idea why they are not being ignored as I see them in the .gitignore file in the root folder

**Comment by robstoll** [comment]
This usually happens if you have added them before you have committed the .gitignore file. I think it is also enough if you have done a `git add .idea` (or similar) and then `git add .gitignore`.
Git ignores the `.gitignore` file in such a case as you have added it explicitly. However, once you remove it again and do a `git add .` (add all changes files) it is not including an file on the .gitignore list only if you add it explicitly again. E.g. with `git add .idea`

**Comment by robstoll** [comment]
The `.gradle` is the only remaining thing, otherwise it looks good to me :+1:

**Comment by bsemexan** [comment]
Last login: Tue Dec 17 08:02:26 on ttys000
berr@mbp ~ % cd atrium
berr@mbp atrium % mv .gradle ../atrium-gradle
berr@mbp atrium % git add .
berr@mbp atrium % git commit -m "remove .gradle folder"
On branch junit5
Your branch is up to date with 'origin/junit5'.

nothing to commit, working tree clean
berr@mbp atrium % git push 
Everything up-to-date

**Comment by robstoll** [comment]
Right, the .gradle folder is in the samples project. Try the following
```
rm -r samples/jvm/junit5/.gradle
git add .
git commit -m "remove .gradle folder"
git push
```
the .gradle folder should usually be recreated again once you hit `gradlew` inside the junit5 folder

**Comment by robstoll** [comment]
@bsemexan Thanks for taking the time for this PR even though are busy lately :slightly_smiling_face: 
There are more issues where Atrium needs help:
https://github.com/robstoll/atrium/issues?q=is%3Aissue+is%3Aopen+label%3A%22good+first+issue%22+no%3Aassignee

The following is very similar to the one you did here:
https://github.com/robstoll/atrium/issues/81

**Pull request merged**
