### PR TITLE
Fix infix api for "List last"

### PR DESCRIPTION
**Pull request by constantine-zubrilin**
Implementation based on this comment https://github.com/robstoll/atrium/pull/1708#issuecomment-1953686058
______________________________________
I confirm that I have read the [Contributor Agreements v1.0](https://github.com/robstoll/atrium/blob/main/.github/Contributor%20Agreements%20v1.0.txt), agree to be bound on them and confirm that my contribution is compliant.

### CODE REVIEW

**Comment by robstoll** [comment]
LGTM do you want to merge this already and make the move to iterable in a separate PR?

**Comment by constantine-zubrilin** [comment]
Moving to iterable is a bit more difficult than I expected. So yes, let's merge this PR, and continue with a new one. Thank you!

**Comment by robstoll** [comment]
@constantine-zubrilin let me know in case you need help

**Comment by robstoll** [comment]
@constantine-zubrylin I planned to release Atrium 1.2.0 in the next few weeks. Shall I take over and do the move from list to iterable or can I help somehow?

**Comment by constantine-zubrylin** [comment]
@robstoll I think I will finish it before March 10. If it's too late, then it's better if you do it yourself I'm afraid

**Comment by robstoll** [comment]
no that's good 🙂👍

**Pull request merged**
