### PR TITLE
#416 move jvm common

### PR DESCRIPTION
**Pull request by assaflei**
started work on domain classes, currently build fails with unresolved references
______________________________________
I confirm that I have read the [Contributor Agreements v1.0](https://github.com/robstoll/atrium/blob/master/.github/Contributor%20Agreements%20v1.0.txt), agree to be bound on them and confirm that my contribution is compliant.

### CODE REVIEW

**Comment by robstoll** [comment]
atrium/domain/robstoll-lib/atrium-domain-robstoll-lib-js/build.gradle => change 
```
testImplementation prefixedProject('verbs-internal-js')
```
to 
```
testImplementation prefixedProject('specs-js')
```

**Comment by assaflei** [comment]
done with domain, will check specs
btw can you explain shortly why did the change to js gradle did the trick? (if its too complicated to explain its ok)

**Comment by robstoll** [comment]
specs-js defines a dependency on spek as well as verbs-internal-js.

**Comment by robstoll** [comment]
Hard to know without knowing the project. However, most of the time it helps to look how the other platform specific modules are defined. For instance jvm defined a dependency on specs-jvm. That would have been a hint

**Comment by assaflei** [comment]
I understand that connection between jvm to specs-jvm, there is a usage of specs-common in common project which seems to relate to this.
Since building of common project failed, I dont understand why a change in js project resolved the problem

**Comment by robstoll** [comment]
No idea what error you had in a common module, the build failed in js:
https://travis-ci.com/github/robstoll/atrium/jobs/317930541#L1214

So maybe bad luck.

**Comment by assaflei** [comment]
I actually didnt notice that, just saw the file where the error occurred and thought it was related to this project... thanks for pointing that out

**Pull request merged**
