### PR TITLE
Draft: Move from tutteli-gradle-dokka to plain dokka 1.4

### LINKED ISSUE #641: update to new dokka plugin
## Non-Code related feature
Atrium is currently using dokka 0.9.8 via the tutteli-dokka plugin. 
We would like to update to dokka 1.4.10

Following the things we need to do (see https://github.com/robstoll/atrium/pull/683 most likely you can build on this):
- [ ] remove `classpath "ch.tutteli:tutteli-gradle-dokka:$tutteli_plugins_version"`  from build.gradle
- [ ] configure the new dokka plugin instead. You don't have to bother what was configured before, you can start from scratch but we have the following requirements:
  - [ ] we need only the html report (disable the rest)
  - [ ] make sure it is not included in the normal build (./gradlew build should not trigger it) - might be this is already the case. Use ` ./gradlew atrium-core-api-jvm:build --dry-run` and check if dokka is included. If it is, then find ways to deactivate it. We want to be able to run dokka separately
  - [ ] check if the samples for toBe are correctly rendered
- [ ] we still want an overall report when running ghPages. You probably need to adapt gradle/scripts/gh-pages.gradle  => see https://github.com/Kotlin/dokka/blob/master/runners/gradle-plugin/MIGRATION.md and https://github.com/Kotlin/dokka#multi-module-projects
  => make sure we still suppress the packages defined at the end of the gh-pages.gradle script.

*Hint*, the following might help to setup the plugin, note thought that Atrium is using groovy and not kotlin for gradle
https://github.com/Kotlin/dokka#using-dokka

## Your first contribution?
- Write a comment `I'll work on this` if you would like to take this issue over. 
  This way we get the chance to revise the description in case things have changed in the meantime, we might give you additional hints and we can assign the task to you, so that others do not start as well.
- See [Your first code contribution](https://github.com/robstoll/atrium/blob/master/.github/CONTRIBUTING.md#your-first-code-contribution) for guidelines.  
- Do not hesitate to ask questions here or to contact us via [Atrium's slack channel](https://kotlinlang.slack.com/team/U3DE1TXKP) if you need help
  ([Invite yourself](https://slack.kotlinlang.org/) in case you do not have an account yet).

### PR DESCRIPTION
**Pull request by jgrgt**
Attempt to fix  #641. Kind of strugling with the submodules. But this produces some code documentation already. Though it does not look very nice...

Some things are commented out for now, they seem to make dokka go into an infinite loop... So there's still work to be done.
______________________________________
I confirm that I have read the [Contributor Agreements v1.0](https://github.com/robstoll/atrium/blob/master/.github/Contributor%20Agreements%20v1.0.txt), agree to be bound on them and confirm that my contribution is compliant.

### CODE REVIEW

**Comment by robstoll** [comment]
@jgrgt I suggest you write in the dokka channel on kotlinlang.slack.com in case you encounter a strange behaviour with dokka. I am sure they can help better than I can.

**Comment by robstoll** [comment]
@jgrgt any progress here?

**Comment by jgrgt** [comment]
@robstoll Sorry, no. Did not get a response on the dokka Slack. And I will not have the time to dig into this further in the short term. Feel free to close this and unassign me from the issue...

**Comment by robstoll** [comment]
ok, closing it, maybe I can still use part of it. We will see, currently I don't have time neither. thanks already for this :+1:

**Pull request closed without merging**
