### PR TITLE
WIP #193 upgrade spek to 2.0.8 and use spek's `include`

### PR DESCRIPTION
**Pull request by Anubhav007**
----
I confirm that I have read the [Contributor Agreements v1.0](https://github.com/robstoll/atrium/blob/master/.github/Contributor%20Agreements%20v1.0.txt), agree to be bound on them and confirm that my contribution is compliant.

### CODE REVIEW

**Comment by robstoll** [comment]
Have a look at the output of the build it clearly states what is wrong, it cannot find
```
import ch.tutteli.atrium.specs.include
```
because that is the one you removed in step 1 :slightly_smiling_face: 
Thus you need to remove this line

**Comment by Anubhav007** [comment]
@robstoll I actually removed those imports but I was still getting errors wherever the include was used. Looks like gradle was not refreshing . The issue got resolved by upgrading the intelliJ. I will raise PR with the changes in a while.

**Comment by robstoll** [comment]
You need to re-import a gradle project in Intellij if you modify something in a build.gradle file

**Comment by robstoll** [comment]
@Anubhav007 try if spek 2.0.7 works

**Comment by Anubhav007** [comment]
@robstoll Looks like only travis build is failing on updating to 2.0.7

**Comment by robstoll** [comment]
@Anubhav007 looks already much better (I guess there is a bug in spek 2.0.8 , I'll investigate later). As last step you have to include the signature of `include` to org.spekframework.spek2.dsl.Root in /misc/specs/atrium-specs-js/src/main/kotlin/org/spekframework/spek2/dsl/Root.kt

**Comment by Anubhav007** [comment]
@robstoll Could you help me with the signature part?

**Comment by robstoll** [comment]
Just copy the signature from spek. Open up a spec and navigate to the definition of `include`

**Comment by Anubhav007** [comment]
@robstoll The build is passing now

**Comment by robstoll** [comment]
@Anubhav007 thanks for your contribution :+1:

**Pull request merged**
