### PR TITLE
[WIP] Upgrade Gradle and Wrapper

### LINKED ISSUE #217: update gradle-wrapper to latest version
## Code related feature

- update the gradle wrapper
- rename the resulting `gradlew` back to `gr`/`gr.bat`

## Your first contribution?
- Write a comment `I'll work on this` if you would like to take this issue over. 
  This way we get the chance to revise the description in case things have changed in the meantime,
  we might give you additional hints and we can assign the task to you, so that others do not start as well.
- See [Your first code contribution](https://github.com/robstoll/atrium/blob/master/.github/CONTRIBUTING.md#your-first-code-contribution) for guidelines.  
- Do not hesitate to ask questions here or to contact us via [Atrium's slack channel](https://kotlinlang.slack.com/team/U3DE1TXKP) if you need help
  ([Invite yourself](https://slack.kotlinlang.org/) in case you do not have an account yet).

### PR DESCRIPTION
**Pull request by piyushmor**
Signed-off-by: Piyush Mor <piyush.mor@gmail.com>

Fixes #217 
----
I confirm that I have read the [Contributor Agreements v1.0](https://github.com/robstoll/atrium/blob/master/.github/Contributor%20Agreements%20v1.0.txt), agree to be bound on them and confirm that my contribution is compliant.

### CODE REVIEW

**Comment by robstoll** [comment]
@piyushmor have you tried to import gradle again? does it work?

**Comment by piyushmor** [comment]
oops! on it.

**Comment by piyushmor** [comment]
@robstoll need some hep with the robstoll-lib-js
`// it is up to the consumer of atrium-core-robstoll-lib which atrium-translations module is used at runtime`
Can you please give me some pointers on how to this is working and how I can help gradle pick the right dependency here?

**Comment by piyushmor** [comment]
Also, build is failing for nodejs not sure if it is related to the gradlew upgrade

**Comment by piyushmor** [comment]
IJ is failing to resolve the correct dependency to load here as there are multiple ones possible. Is it possible to specify a more specific dependency here?

**Comment by robstoll** [comment]
there are currently two translations modules, for JS these are atrium-translations-en_GB-js and atrium-translations-de_CH-js. atrium-core-robstoll-lib has only a compileOnly dependency (so that they can be replaced) and the bundle modules choose the actual translation (e.g. atrium-fluent-en_GB-js is using atrium-translations-en_GB-js).

I cannot help you with helping gradle, I would need to read up on what changed in gradle 5.6 as well (and then I could to the task myself). 
About nodejs, you could try to update this dependency as well, maybethe current version isn't compatible with gradle 6.0

**Comment by robstoll** [comment]
@piyushmor could you find out anything?

**Comment by robstoll** [comment]
Closing this as I there seems to be no progression on this PR anymore

**Pull request closed without merging**
