### PR TITLE
#430 Deprecate api-cc-infix add replacements for api-infix anyInsertions

### PR DESCRIPTION
**Pull request by Miftahunajat**
This PR add Deprecate api-cc-infix and add `Replacewith` for the expect in anyInsertions
______________________________________
I confirm that I have read the [Contributor Agreements v1.0](https://github.com/robstoll/atrium/blob/master/.github/Contributor%20Agreements%20v1.0.txt), agree to be bound on them and confirm that my contribution is compliant.

### CODE REVIEW

**Comment by Miftahunajat** [comment]
The previous build have errors when I add the _deprecated_ annotation.
so I have to try to add `@file:Suppress("DEPRECATION" /* will be removed with 1.0.0 */)` in some Test files.
What is your opinion? @robstoll

**Comment by robstoll** [comment]
Thanks for the PR, I see that I should have prepared a few things beforehand - like suppressing deprecations in the tests of core-common. We will remove those deprecations once we have deprecated cc-infix and migrate the core modules to the new infix API. But that will be an issue we tackle after this one.

I have made the adjustments now. Please rebase on master. Last but not least I would like to see the replacement in action. My description in the issue was not good enough, I have improved it. The goal is to use it in the tests so that we can be sure that they actually work. I should have done that for cc-en_GB but did not have the time. So it could be that we will reveal a few bugs and can fix those. For a starter, I realised that the deprecation of `and` does not really make sense, so I removed it from cc-en_GB, please do the same in your PR.

**Comment by Miftahunajat** [comment]
Okay I will try it out

**Comment by Miftahunajat** [comment]
Hello @robstoll 
Sorry for asking again
Is this replaceWith expression is correct?
`"this.asExpect().toBe(expected).asAssert()"`
Because when I replace some of spec with this. The `.asAssert()` part is deprecated also.
and I'm not sure about to replace it.

**Comment by robstoll** [comment]
Just ask, no problem. `asAssert` is deprecated and you don't have to replace it. That's also the reason why you need to suppress deprecations in the end (re-add `@file: Suppress (...)`). The reason why we have `asAssert` is that one can use own assertion functions which are based on Assert. If one uses such a function in a fluent call chain but still wants to migrate Atrium's functions to the new API which is based on Expect. Unfortunately it's not possible to detect in a ReplaceWith if there is a method call following or not.

**Comment by Miftahunajat** [comment]
When I use the ALT+ENTER shortcut to replace the usages in test.
for example in `toBe` it imports `ch.tutteli.atrium.api.fluent.en_GB.toBe` instead of `ch.tutteli.atrium.api.infix.en_GB.toBe`.
When I try to write the asExpect manually it doesn't have shortcut for toBe in `infix` packages in anyAssertion spec.
am I did something wrong in the steps?

**Comment by robstoll** [comment]
I'll have a look tomorrow. The `import` part sounds like an awkward Kotlin bug - though I have in mind I tried it out as well and it worked. What Intellij version are you using?

**Comment by robstoll** [comment]
I have a wild guess, maybe it's due to the new type inference system. Check in your Intellij preference, search for kotlin compiler and uncheck `enable new...`. see if it works then. If it does then it's good enough. Let me know about the result

**Comment by Miftahunajat** [comment]
I already uncheck the `Enable new type inference algorithm for IDE analysis` but the error still.
When I manually import the `ch.tutteli.atrium.api.infix.en_GB` in anyAssertionsSpec it gives me error Unsolved reference: infix
image

**Comment by robstoll** [comment]
Sorry, totally my fault. I forgot to add the dependency to the new infix API in tests of cc-infix

**Comment by Miftahunajat** [comment]
Oh I wish I knew earlier that the problem is with the dependency.
I will try to add the dependency on this PR then.

**Comment by robstoll** [comment]
Sorry about that, I fixed it for core but forgot the API. You can copy from this commit: https://github.com/robstoll/atrium/commit/47facb86ebfa0340ae7d0a304f05a10738dad1d7

Wait... I the commit already adds it; and I thought I was day dreaming 😅
The problem must be elsewhere. Have you rebased on master?

**Comment by Miftahunajat** [comment]
Thank you
The problem gone as I rebuild it after rebasing.

**Comment by robstoll** [comment]
Ah good. 
Note, in case you rebase again: you need to update intellij to 2020.1

**Comment by robstoll** [comment]
Oho... more things I forgot as it seems. Please add `@file:Suppress("DEPRECATION" /* will be removed with 1.0.0 */)` to:
- bundles/cc-infix-en_GB-robstoll/atrium-cc-infix-en_GB-robstoll-common/src/test/kotlin/SmokeTest.kt
- bundles/cc-infix-en_GB-robstoll/atrium-cc-infix-en_GB-robstoll-jvm/src/test/kotlin/custom/SmokeSpec.kt

**Comment by robstoll** [comment]
@Miftahunajat thanks for the first step in deprecating cc-infix. Looking forward to the next PR :slightly_smiling_face:

**Comment by Miftahunajat** [comment]
Okay, since there are still many files left. May I will create several PR with several files.

**Comment by Miftahunajat** [comment]
Hello @robstoll sorry for late response
I have a small problem with deprecating arrayAssertion on atrium-api-cc-infix-en_GB.
When I replace the usage of `asIterable` with `this.asExpect().asList().asAssert()` (I copied from atrium-api-infix-en_GB) it gives error message, because there is no such function on `asList()` without any argument on it.
Is there a function for an `asList()` call without any argument on it?
or should I replace the call with `asList(o)`? because there is function for that.

**Comment by robstoll** [comment]
No worries. Please use `asList(o)` and don't forget to add the import for `o` to the replacement

**Pull request merged**
