### PR TITLE
#649 add samples for floatingPointAssertions of api-fluent

### PR DESCRIPTION
**Pull request by BimuratMukhtar**
______________________________________
I confirm that I have read the [Contributor Agreements v1.0](https://github.com/robstoll/atrium/blob/master/.github/Contributor%20Agreements%20v1.0.txt), agree to be bound on them and confirm that my contribution is compliant.

### CODE REVIEW

**Comment by BimuratMukhtar** [comment]
Note: I have not checked this tests locally, because was unable to run tests locally: 
1) tried to run test from intellije idea but it showed a popup with message **Nothing Here**
2) tried to run this task `:atrium-api-fluent-en_GB-common:test` by ./gradlew and gradle from terminal

Could you help? How to run this tests?

**Comment by robstoll** [comment]
You can run the tests with `./gradlew :atrium-api-fluent-en_GB-jvm:test`

**Comment by BimuratMukhtar** [comment]
> You can run the tests with `./gradlew :atrium-api-fluent-en_GB-jvm:test` - or with `...-js` where each test is listed

thanks, checked out locally: all tests passed including tests in FloatingPointAssertionSamples.kt

**Comment by robstoll** [comment]
Could you please do the following. For whatever reason travis did not kick in:
```
git ci --amend --no-edit && git push -f
```

**Comment by BimuratMukhtar** [comment]
> Could you please do the following. For whatever reason travis did not kick in:
> 
> ```
> git ci --amend --no-edit && git push -f
> ```

done, why travis should kick in?

**Comment by robstoll** [comment]
Travis is the CI we use. I guess it was just down the moment github notified. Now we have 8 checks including travis where before we only had 7

**Review by robstoll — APPROVED** [review]

**Comment by robstoll** [comment]
@BimuratMukhtar thanks for your first contribution to Atrium 🙂👍

Nice to see, that you are already working on two others. And please don'tont forget to ⭐ Atrium

**Comment by BimuratMukhtar** [comment]
> @BimuratMukhtar thanks for your first contribution to Atrium 
> 
> Nice to see, that you are already working on two others. And please don'tont forget to  Atrium

thank you too for useful feedback, already starred Atrium, could you please close related issue or label my merged PR as hacktoberfest-accepted in order to make it counted in challenge

**Comment by robstoll** [comment]
They should count once merged no?
Going to close the issues, thanks for the reminder

**Comment by BimuratMukhtar** [comment]
i also thinked it should count after merge, but status is in review. right now searched and found update https://hacktoberfest.digitalocean.com/hacktoberfest-update
image

**Comment by robstoll** [comment]
All good then, if it is in review it means it will be accepted soon. This repo has the topic hacktoberfest

**Comment by BimuratMukhtar** [comment]
ok, thanks

**Pull request merged**
