### PR TITLE
#416 move jvm common

### PR DESCRIPTION
**Pull request by assaflei**
I switched to lineSeperator and moved ToStringObjectFormatter
Tried moving other classes but encountered errors due to using System or KClass reflection

______________________________________
I confirm that I have read the [Contributor Agreements v1.0](https://github.com/robstoll/atrium/blob/master/.github/Contributor%20Agreements%20v1.0.txt), agree to be bound on them and confirm that my contribution is compliant.

### CODE REVIEW

**Comment by robstoll** [comment]
I guess you would like to tackle the problem, so here my hints:
As far as I can see TextListBasedAssertionGroupFormatterSpec is using `Class` instead of `KClass`, that's a problem for common. You could rewrite TextListBasedAssertionGroupFormatterSpec to use KClass instead. However, it depends on TranslatorIntSpec which needs a bit more in order that it can be moved, so I would do this in another PR. Which means you can keep TextListBasedAssertionGroupFormatterSpec and TextListAssertionGroupFormatterSpec in specs-jvm (and TextListAssertionGroupFormatterSpec in atrium-core-robstoll-lib-jvm). Same applies to TextFeatureAssertionGroupFormatterSpec, it also depends on TranslatorIntSpec. However, you should be able to move all other classes.

The problem with KClass reflection can be solved by using `fullName` instead of `qualifiedName!!`

I am not sure what you mean with 
> errors due to using System

**Comment by assaflei** [comment]
Moved all other classes, I will now try to handle TranslatorIntSpec and related classes.
Regarding System namespace, there are classes such as core\robstoll-lib\atrium-core-robstoll-lib-jvm\src\test\kotlin\ch\tutteli\atrium\core\robstoll\lib\reporting\DetailedObjectFormatterSpec.kt using commands such as `System.identityHashCode(string)` which requires them to stay at jvm project. We discussed about similar commands before (System.getProperty) and I left these classes in place.

**Comment by robstoll** [comment]
:+1: merged this already so that we don't run into conflicts.

**Comment by robstoll** [comment]
> Regarding System namespace, there are classes such as core\robstoll-lib\atrium-core-robstoll-lib-jvm\src\test\kotlin\ch\tutteli\atrium\core\robstoll\lib\reporting\DetailedObjectFormatterSpec.kt using commands such as System.identityHashCode(string) which requires them to stay at jvm project. 

I see, keep DetailedObjectFormatterSpec in the jvm module then.

**Comment by robstoll** [comment]
Note, you need to update IntelliJ to 2020.1 when you base your next PR on master.

**Comment by robstoll** [comment]
> I will now try to handle TranslatorIntSpec and related classes.

IMO thos os not a must. We need to rework translation anyway (it is too much JVM based) and therefore it would be totally fine to leave it and dependent classes in JVM.

**Comment by assaflei** [comment]
> Note, you need to update IntelliJ to 2020.1 when you base your next PR on master.

I'm using VS code so not relevant

> > I will now try to handle TranslatorIntSpec and related classes.
> 
> IMO this is not a must. We need to rework translation anyway (it is too much JVM based) and therefore it would be totally fine to leave it and dependent classes in JVM.

So we can close the issue don't we?

**Comment by robstoll** [comment]
> I'm using VS code so not relevant

Interesting, what's your experience so far?

> So we can close the issue don't we?

Might well be, I'll check later if we have covered everything.

**Comment by robstoll** [comment]
all done, I closed the issue. I could use your help for other issues, for instance: 
https://github.com/robstoll/atrium/issues/245 would be great, or one which is maybe a bit tougher but actually more valuable https://github.com/robstoll/atrium/issues/167
But there are more:
https://github.com/robstoll/atrium/issues?q=is%3Aissue+is%3Aopen+label%3A%22help+wanted%22

**Comment by assaflei** [comment]
Regarding the VS code, the experience is good since its working and not only for java related project.
I love the idea of one app for all types of devs.
Although there is the issue of not knowing what I'm missing by not using specialized tool for this eco system.

Happy to help with closing of the issue, I'll try to upgrade the level step by step so will check 245 first

**Pull request merged**
