### PR TITLE
working on OnlyFailureReporterSpec

### PR DESCRIPTION
**Pull request by assaflei**
Used mockk just Runs command for verify action
Please approve if all is valid and I will finish this task

----
I confirm that I have read the [Contributor Agreements v1.0](https://github.com/robstoll/atrium/blob/master/.github/Contributor%20Agreements%20v1.0.txt), agree to be bound on them and confirm that my contribution is compliant.

### CODE REVIEW

**Comment by robstoll** [comment]
Looks good to me

**Comment by assaflei** [comment]
Done
Whats next?

**Comment by robstoll** [comment]
Thanks :slightly_smiling_face: 
I would continue with the `Text...Specs` in the package `ch.tutteli.atrium.specs.reporting`. Might well be that you have to migrate all at once. 
Note, in case I should not reply quickly you can basically migrate any spec which still uses Spek 1.x Search for `import org.jetbrains.spek.api.Spek` and you will find them

**Comment by assaflei** [comment]
Ok I'll try
The class TextIndentBasedAssertionGroupFormatterSpec is marked as not needed for spek migration but it breaks build since other classes are dependent of it
What do you say?

**Comment by robstoll** [comment]
Just delete it, it's not worth to migrate it.

**Comment by assaflei** [comment]
delete the file? (misc\specs\atrium-specs-jvm\src\main\kotlin\ch\tutteli\atrium\specs\reporting\TextIndentBasedAssertionGroupFormatterSpec.kt) and remove the include blocks using it?

**Comment by robstoll** [comment]
wait, that's not the one I was thinking of :laughing: give me a minute

**Comment by robstoll** [comment]
Delete ch.tutteli.atrium.core.robstoll.lib.reporting.TextIndentAssertionGroupFormatterSpec
but keep and migrate ch.tutteli.atrium.specs.reporting.TextIndentAssertionGroupFormatterSpec -- the `//TODO remove with 1.0.0 - no need to migrate to spek2` was wrong, you can remove that TODO as well

**Comment by assaflei** [comment]
see this class: misc\specs\atrium-specs-jvm\src\main\kotlin\ch\tutteli\atrium\specs\reporting\TextExplanatoryBasedAssertionGroupFormatterSpec.kt
when upgrading to new spek, build fails due to the other class

**Comment by robstoll** [comment]
btw. I just realised that the specs you migrated are still under specs-jvm. Can you please move them to atrium-specs-common. Thanks

**Comment by assaflei** [comment]
you mean reporting folder in specs-jvm to similar folder in specs-common?

**Comment by robstoll** [comment]
for instance, move 
misc/specs/atrium-specs-jvm/src/main/kotlin/ch/tutteli/atrium/specs/reporting/ObjectFormatterSpec.kt
to
/misc/specs/atrium-specs-common/src/main/kotlin/ch/tutteli/atrium/specs/reporting/ObjectFormatterSpec.kt

**Comment by robstoll** [comment]
> see this class: misc\specs\atrium-specs-jvm\src\main\kotlin\ch\tutteli\atrium\specs\reporting\TextExplanatoryBasedAssertionGroupFormatterSpec.kt
when upgrading to new spek, build fails due to the other class

with other class you mean the subclasses right? you need to migrate them as well. That's what I meant with you probably need to migrate all of them at once

**Comment by assaflei** [comment]
I started moving classes from specs-jvm to specs-common
Than I get these errors: "Unresolved reference: System" and "Unresolved reference: java"
It looks like a gradle related issue, can you advice which configuration should be used?

**Comment by robstoll** [comment]
As I don't know which class you moved I can only guess that you tried to move a spec which is actually jvm specific. I think you should be able to move ObjectFormatterSpec and OnlyFailureReporterSpec

**Comment by assaflei** [comment]
So in case of jvm dependencies, leave the classes there?

**Comment by robstoll** [comment]
normally yes, but sometimes it could also be that we used the wrong type. For instance java.util.Collection instead of kotlin.Collection. I need the class to be able to judge

**Comment by assaflei** [comment]
In OnlyFailureReporterSpec I get Unresolved reference: java for this command assertionFormatterFacade::class.java.simpleName
So same jvm dependency here?

**Comment by robstoll** [comment]
you can use `::class.simpleName` instead

**Pull request merged**
