### PR TITLE
Change Github Emoji to Unicode emoji

### PR DESCRIPTION
**Pull request by Frandall**
Replace emoji that was defined using github markup with unicode based emoji

----
I confirm that I have read the [Contributor Agreements v1.0](https://github.com/robstoll/atrium/blob/master/.github/Contributor%20Agreements%20v1.0.txt), agree to be bound on them and confirm that my contribution is compliant.

### CODE REVIEW

**Comment by robstoll** [comment]
@Frandall First of all, thank you very much for your contribution. :slightly_smiling_face: :+1:
I need your opinion, I am no longer sure.... I am disappointed how my browser (firefox) renders ⚠ , it's not even yellow :cry: 
:warning: looks much better.  I am no longer sure if it is a good idea to change the icons to utf-8. The primary usage is github. What do you think?

Or maybe we could change these icons to something else. Following a suggestion, but maybe you come up with a better one:
- :warning:  => 😱
- :information_source: => 💬
- :interrobang: => 🤔

**Comment by Frandall** [comment]
Well, from your issue, you concern about external sites not rendering properly. What external sites that you had found not rendering it correctly?

**Comment by robstoll** [comment]
Sad enough I don't remember

**Comment by Frandall** [comment]
If you want to change the icon, I think we need to find more suitable than 
⚠️ => 😱
ℹ️ => 💬
⁉️ => 🤔

**Comment by robstoll** [comment]
ideas?

**Comment by Frandall** [comment]
How about
⚠️ => ❗
ℹ️ => 👓
⁉️ => 💬

**Comment by robstoll** [comment]
Yeah... go for it. 
Just one note about your change though. I would prefer if you could use utf-8 characters instead of escaping sequences. Or have you done this for a particular reason?

**Comment by robstoll** [comment]
what browsers do you have in mind?

**Comment by Frandall** [comment]
I mainly use chrome ^^

**Comment by robstoll** [comment]
I mean what browser do you have in mind which do not support utf8 characters yet

**Comment by Frandall** [comment]
Hmm, I think in this case all of them support utf8, because people who find this will have some degree of knowledge to use the latest of popular browser. I think I will use the utf-8 character.

**Comment by robstoll** [comment]
LGTM, thank you very much for the discussion and contribution :slightly_smiling_face:

**Comment by robstoll** [comment]
Fancy another one? Have a look at https://github.com/robstoll/atrium/issues?q=is%3Aissue+is%3Aopen+label%3A%22good+first+issue%22 e.g. 160

**Comment by Frandall** [comment]
I'll let you know in 3 days.

**Pull request merged**
